const cartTypes = {
  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
  CART_CLEAR_ITEM: "CART_CLEAR_ITEM",
  CART_DECREASE_ITEM_QTY: "CART_DECREASE_ITEM_QTY",
  CART_REMOVE_ALL_ITEMS: "CART_REMOVE_ALL_ITEMS",
  CART_SHIPPING_ADDRESS: "CART_SHIPPING_ADDRESS",
  CART_PAYMENT_METHOD: "CART_PAYMENT_METHOD",
};

export default cartTypes;
